export const SET_CATEGORY = 'SET_CATEGORY';
export const SET_CLOTHES = 'SET_CLOTHES';
export const ADD_ITEMS_CART = 'ADD_ITEMS_CART';
export const SET_TOTAL_PRICE = 'SET_TOTAL_PRICE';
export const SET_TOTAL_COUNT = 'SET_TOTAL_COUNT';
